#!/bin/sh

printf 'Enter your username: '
read -r user

secret_key="$(openssl rand 19)"
secret="$(echo -n $secret_key | base32 | tr -d '=')"

printf '%s:%s\n' "${user:-user}" "$secret" > secrets 

echo "$PWD/secrets"
